---
booktitle: Proceedings of the Seventh Workshop on Conformal and Probabilistic Prediction
  and Applications
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: COPA
volume: 91
year: '2018'
start: 2018-06-11
end: 2018-06-13
url: http://proceedings.mlr.press
author:
  name: PMLR
location: Maastricht, Netherlands
published: 2018-06-07
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: COPA-2018
month: 0
cycles: false
editor:
- given: Alex
  family: Gammerman
- given: Vladimir
  family: Vovk
- given: Zhiyuan
  family: Luo
- given: Evgueni
  family: Smirnov
- given: Ralf
  family: Peeters
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Seventh Workshop on Conformal and Probabilistic Prediction and Applications on 11-13 June 2018

  Published as Volume 91 by the Proceedings of Machine Learning Research on 07 June 2018.

  Volume Edited by:
    Alex Gammerman
    Vladimir Vovk
    Zhiyuan Luo
    Evgueni Smirnov
    Ralf Peeters

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 11--13 Jun
baseurl: "/v91"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v91
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Conformal and Probabilistic Prediction and Applications
  url: 
  location: 
  dates:
  - 2018-06-11
  - 2018-06-12
  - 2018-06-13
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
